Added Bootstrap to style/format all pages
adelwu/team-18-codeu pull request #28
Opened 2019-06-24 03:43 UTC by adelwu

<img width="1422" alt="Screen Shot 2019-06-23 at 10 41 03 PM" src="https://user-images.githubusercontent.com/33011294/59990278-15bb1e00-9608-11e9-9cfa-ab331a44cd1e.png">
<img width="1427" alt="Screen Shot 2019-06-23 at 10 40 54 PM" src="https://user-images.githubusercontent.com/33011294/59990279-15bb1e00-9608-11e9-9578-22c2599c1855.png">
Ah I totally forgot I needed to make a new branch!! Please ignore all these previous commits. I just pushed my commit for Bootstrap.

2019-06-24 17:07 UTC, dhgarrette requested changes
This is so cool!  The code looks good but the branch appears to need syncing: `git pull origin master`

2019-06-25 16:23 UTC, dhgarrette requested changes

2019-06-25 16:23 UTC, dhgarrette commented on src/main/webapp/aboutus.html
> +<<<<<<< HEAD
Looks like it got committed before the merging was completed.

2019-06-25 16:23 UTC, dhgarrette commented on src/main/java/com/google/codeu/servlets/MessageServlet.java
> +      response.sendRedirect("/index.html");
A random space got added to the end of the line here.

2019-06-25 20:50 UTC, adelwu commented on src/main/webapp/css/main.css
> +>>>>>>> 81a5143a9def2d01e53ac7d2825075d6851dfc4f
I don't know why this is showing up, I they're not showing on my computer and I remember deleting them?

2019-06-26 15:02 UTC, dhgarrette commented on src/main/webapp/css/main.css
> +>>>>>>> 81a5143a9def2d01e53ac7d2825075d6851dfc4f
Hmm, maybe try doing a `git pull` in case what's on your computer doesn't match what's on github?  What kind of text editor are you using to view the file?  Maybe your IDE is hiding those lines or something?

2019-07-02 04:00 UTC, dhgarrette approved these changes

2019-07-02 04:03 UTC, merged