Iram dev
adelwu/team-18-codeu pull request #31
Opened 2019-07-08 03:25 UTC by iramsharieff06

I added the base for the back-end logic! I am going to get started on testing different things and adding data to the dataset (hard-coded).

2019-07-09 15:23 UTC, dhgarrette requested changes

2019-07-09 15:23 UTC, dhgarrette commented on src/main/java/com/google/codeu/data/Hub.java
> +
This seems like the kind of thing that could cause problems since it's unclear if it's supposed to be latitude/longitude or longitude/latitude.  Let's make things easier and split it into two fields: `gpsLatitude` and `gpsLongitude`.  That will also fix the TravisCI failure that's happing because it doesn't know what `javafx.util.Pair` is.  Alternatively you could make a special class with fields named `latitude` and `longitude`, bu that's probably excessive.

2019-07-13 21:57 UTC, iramsharieff06 commented
I just updated the data representation!

2019-07-13 22:14 UTC, iramsharieff06 reviewed
I left a comment but I need to add a method to datastore that checks if a hub is already stored.

2019-07-14 20:49 UTC, dhgarrette approved these changes

2019-07-14 20:49 UTC, dhgarrette commented on src/main/java/com/google/codeu/data/Hub.java
> +import javafx.util.Pair;
You can remove this import now.

2019-07-14 20:49 UTC, dhgarrette commented on src/main/java/com/google/codeu/servlets/HubListServlet.java
> +      //need to add to datastore if not already there
You could retrieve all hubs from the datastore, make a Set out of them, and check whether each one you are adding is already in the set.  It might be sufficient to just store one key field in the set; maybe `address` if we assume that's going to be unique?

2019-07-14 20:51 UTC, dhgarrette requested changes

2019-07-14 20:51 UTC, dhgarrette commented on src/main/java/com/google/codeu/data/Datastore.java
> +    // need to get information from the file?
You can remove this comment since it's now handled in the servlet.

2019-07-18 03:29 UTC, dhgarrette approved these changes

2019-07-19 02:16 UTC, merged