Iram dev
adelwu/team-18-codeu pull request #7
Opened 2019-05-28 18:57 UTC by iramsharieff06

Updates to Datastore implementation to retrieve list of users for user list page.

2019-05-28 19:02 UTC, dhgarrette requested changes
Thanks, Iram!  I added a couple of minor comments.

2019-05-28 19:02 UTC, dhgarrette commented on src/main/java/com/google/codeu/servlets/UserListServlet.java
> +  }
There should be a blank line between method definitions.

2019-05-28 19:02 UTC, dhgarrette commented on src/main/java/com/google/codeu/servlets/UserListServlet.java
> +  //  response.getOutputStream().println("this will be my user list");
You can remove this line since it's no longer needed.  If you ever need to find it again, it will always ben in the file's history :-)

2019-05-28 19:02 UTC, dhgarrette commented on src/main/java/com/google/codeu/data/Datastore.java
> +    public Set<String> getUsers(){
There should be a blank line between method declarations, and this line should be indented exactly two spaces.

2019-05-29 01:20 UTC, iramsharieff06 commented on src/main/java/com/google/codeu/data/Datastore.java
> +    public Set<String> getUsers(){
Sounds good! Thanks for the style tips

2019-05-29 01:36 UTC, dhgarrette requested changes
Thanks, Iram!  A couple more things.

2019-05-29 01:36 UTC, dhgarrette commented on src/main/java/com/google/codeu/servlets/UserListServlet.java
> +   }
Looks like this "}" got an extra space.  It should be indented 2 spaces.

2019-05-29 01:36 UTC, dhgarrette commented on src/main/java/com/google/codeu/servlets/UserListServlet.java
> -      System.out.println(users);
It looks like you lost the `System.out.println(users);` call when you removed the commented out code.

2019-05-29 03:06 UTC, iramsharieff06 commented on src/main/java/com/google/codeu/servlets/UserListServlet.java
> +   }
Sounds good! Just updated it

2019-05-29 03:06 UTC, iramsharieff06 commented on src/main/java/com/google/codeu/servlets/UserListServlet.java
> -      System.out.println(users);
Woops sorry! Just put it back

2019-05-29 04:44 UTC, dhgarrette approved these changes
Looks great, thanks!

2019-05-29 04:46 UTC, merged